name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install | tee install.log

    - name: Run tests
      run: npm test | tee test.log
  
    - name: Debug Environment Variables
      run: env

    - name: Introduce a deliberate failure
      run: exit 1

    - name: Capture logs and analyze with Gemini AI on failure
      if: failure()
      run: |
        echo "Pipeline failed, capturing logs..."
        logs=$(cat install.log test.log)
        echo "$logs" > logs.txt

        python3 -m pip install --upgrade pip
        pip install -q -U google-generativeai
        
        python3 scripts/analyze_logs.py logs.txt
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

   